CareerFairTracker/config/routes.rb
Rails.application.routes.draw do

  get 'admin/dashboard', to: 'admins#dashboard', as: 'admin_dashboard'
  get 'recruiter/dashboard', to: 'recruiters#dashboard', as: 'recruiter_dashboard'
  get 'student/dashboard', to: 'students#dashboard', as: 'student_dashboard'
  
  resources :admins
  delete 'events', to: 'events#destroy'
  resources :events
  resources :recruiters
  root 'home#index'
  post 'users', to: 'users#create', as: 'user'
 
  post 'signup', to: 'users#create', as: 'signup'
  get 'signup', to: 'users#new'
  
  get 'dashboard', to: 'dashboards#index', as: 'dashboard'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  # post '/users' => 'users#create'
  # match '/users', to: 'users#create', as: 'dashboard', via: :post
  # match '/dashboards' => 'dashboards#index', via: :post
  match '/logins' => 'logins#index', via: :get
  match '/logins' => 'logins#index', via: :post
  
  # post '/dashboards/:username/display' => 'dashboards#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :home
  resources :students
  # resources :logins
  resources :dashboards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CareerFairTracker/app/models/recruiter.rb
class Recruiter < ApplicationRecord
  belongs_to :user, optional: true
  # has_secure_password

  # validates :email, presence: true, uniqueness: true
  # validates_presence_of :password_digest, :first_name, :last_name, :company_name
  
end

CareerFairTracker/app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  before_action :set_recruiter, only: [:show, :edit, :update, :destroy]

  def index
    @recruiters = Recruiter.all
  end

  def show
  end

  def new
    @recruiter = Recruiter.new
  end

  def edit
  end

  def create
    @user = User.find(session[:user_id])
    @recruiter = Recruiter.new(recruiter_params)
    @recruiter.user = @user
    @recruiter.user_id = @user.id
    if not @recruiter.save!
      redirect_to root_url and return
    end
    session[:user_id_for_their_type] = @recruiter.id
    redirect_to recruiter_dashboard_path and return
  end

  def dashboard
    @user = current_user
    if @user == nil
      redirect_to root_url and return
    end
    @user_tag = @user[:username]
    @recruiter = Recruiter.find_by user_id: @user.id
    @user_type = @user[:user_type]
    @welcome_message = "Welcome #{@user_tag}"
  end

  def update
    respond_to do |format|
      if @recruiter.update(recruiter_params)
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @recruiter }
      else
        format.html { render :edit }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recruiter.destroy
    respond_to do |format|
      format.html { redirect_to recruiters_url, notice: 'Recruiter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruiter
      @recruiter = Recruiter.find(params[:id])
    end

    def recruiter_params
      params.require(:recruiter).permit(:first_name, :last_name, :company_name, :email, :company_code)
    end
end

CareerFairTracker/app/helpers/recruiters_helper.rb
module RecruitersHelper
end

CareerFairTracker/app/views/recruiters/_form.html.erb
<%= form_with(model: recruiter, local: true) do |form| %>
  <% if recruiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recruiter.errors.count, "error") %> prohibited this recruiter from being saved:</h2>

      <ul>
        <% recruiter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :company_code %>
    <%= form.text_field :company_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

CareerFairTracker/app/views/recruiters/dashboard.html.haml
%h3{:style => "text-align: right; float: right;"}= "#{@userTag}"
%h1{:style => "text-align: center;"}= "#{@user_type} Dashboard" 
%br 
= link_to "Logout", logout_path
%br
%br 
%p= "#{@welcome_message}"
%br
= link_to "Edit Profile", edit_recruiter_path(session[:user_id_for_their_type])
%br 
= button_to "Start Career Fair Mode"

CareerFairTracker/app/views/recruiters/edit.html.erb
<h1>Editing Recruiter</h1>

<%= render 'form', recruiter: @recruiter %>

<%= link_to 'Show', @recruiter %> |
<%= link_to 'Back', recruiters_path %>

CareerFairTracker/app/views/recruiters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recruiters</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Company name</th>
      <th>Email</th>
      <th>Company code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recruiters.each do |recruiter| %>
      <tr>
        <td><%= recruiter.first_name %></td>
        <td><%= recruiter.last_name %></td>
        <td><%= recruiter.company_name %></td>
        <td><%= recruiter.email %></td>
        <td><%= recruiter.company_code %></td>
        <td><%= link_to 'Show', recruiter %></td>
        <td><%= link_to 'Edit', edit_recruiter_path(recruiter) %></td>
        <td><%= link_to 'Destroy', recruiter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recruiter', new_recruiter_path %>

CareerFairTracker/app/views/recruiters/new.html.erb
<h1>New Recruiter</h1>

<%= render 'form', recruiter: @recruiter %>

<%= link_to 'Back', recruiters_path %>

CareerFairTracker/app/views/recruiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @recruiter.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @recruiter.last_name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @recruiter.company_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @recruiter.email %>
</p>

<p>
  <strong>Company code:</strong>
  <%= @recruiter.company_code %>
</p>

<%= link_to 'Edit', edit_recruiter_path(@recruiter) %> |
<%= link_to 'Back', recruiter_dashboard_path %>