CareerFairTracker/config/routes.rb
Rails.application.routes.draw do

  get 'admin/dashboard', to: 'admins#dashboard', as: 'admin_dashboard'
  get 'recruiter/dashboard', to: 'recruiters#dashboard', as: 'recruiter_dashboard'
  get 'student/dashboard', to: 'students#dashboard', as: 'student_dashboard'
  
  resources :admins
  delete 'events', to: 'events#destroy'
  resources :events
  resources :recruiters
  root 'home#index'
  post 'users', to: 'users#create', as: 'user'
 
  post 'signup', to: 'users#create', as: 'signup'
  get 'signup', to: 'users#new'
  
  get 'dashboard', to: 'dashboards#index', as: 'dashboard'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  # post '/users' => 'users#create'
  # match '/users', to: 'users#create', as: 'dashboard', via: :post
  # match '/dashboards' => 'dashboards#index', via: :post
  match '/logins' => 'logins#index', via: :get
  match '/logins' => 'logins#index', via: :post
  
  # post '/dashboards/:username/display' => 'dashboards#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :home
  resources :students
  # resources :logins
  resources :dashboards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CareerFairTracker/app/models/admin.rb
class Admin < ApplicationRecord
    belongs_to :user, optional: true
end

CareerFairTracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CareerFairTracker/app/models/event.rb
class Event < ApplicationRecord
end

CareerFairTracker/app/models/recruiter.rb
class Recruiter < ApplicationRecord
  belongs_to :user, optional: true
  # has_secure_password

  # validates :email, presence: true, uniqueness: true
  # validates_presence_of :password_digest, :first_name, :last_name, :company_name
  
end

CareerFairTracker/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user, optional: true

    def self.to_csv
        attributes = %w(first_name last_name major)

        CSV.generate(headers: true) do |csv|
            csv << attributes

            all.each do |student|
                csv << student.attributes.values_at(*attributes)
            end
        end
    end
end

CareerFairTracker/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :username, presence: true, uniqueness: true
    validates_presence_of :user_type, :password_digest

    has_many :admins, dependent: :destroy
    has_many :students, dependent: :destroy
    has_many :recruiters, dependent: :destroy

    def self.factory(user)
        user_type = user[:user_type]
        if user_type == "Admin"
          newUser = Admin.new()
        elsif user_type == "Student"
          newUser = Student.new()
        elsif user_type == "Recruiter"
          newUser = Recruiter.new()
        end
    end

end

CareerFairTracker/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def show
  end

  def new
    @admin = Admin.new
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def create
    @user = User.find(session[:user_id])
    @admin = Admin.new(admin_params)
    @admin.user = @user
    @admin.user_id = @user.id
    if not @admin.save!
      redirect_to root_url and return
    end
    session[:user_id_for_their_type] = @admin.id
    redirect_to admin_dashboard_path and return
  end

  def dashboard
    if session[:user_id] == nil 
      redirect_to root_url and return
    end
    @events = Event.all
    @user = User.find(session[:user_id])
    @user_tag = @user[:username]
    @admin = Admin.find_by user_id: @user.id
    @user_type = @user[:user_type]
    @welcome_message = "Welcome #{@user_tag}"
  end

  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # only allow specific params from user
    def admin_params
      params.require(:admin).permit(:first_name, :last_name, :email)
    end
end

CareerFairTracker/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @students = Student.all
    @event = Event.find(params[:id])
    @urlString = "#{@event.id}.csv"
    respond_to do |format|
      format.html
      format.csv { send_data @students.to_csv}
    end
    
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_dashboard_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :event_date, :start_time, :end_time)
    end
end

CareerFairTracker/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

CareerFairTracker/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def user_params
    params.permit(:user_type, :username, :password)
  end

  def index
  end

  def show
  end

  def new
  end

  def edit
    if session[:user_id] != nil
      user = User.find(session[:user_id])
      @user_type = user.user_type
      @profile_name = "#{user.username}"
    end
  end
# feel like there could be some bug in create
  def create
    @user = User.new(user_params)
    if not @user.save!
      redirect_to root_url and return
    end
    session[:user_id] = @user.id
    destination = determine_reroute_path_for(@user)
    redirect_to destination and return
  end

  def determine_reroute_path_for(user)
    type = user[:user_type]
    if type == "Admin"
      chosen_path = {controller: 'admins', action: 'new'}
    elsif type == "Student"
      chosen_path = {controller: 'students', action: 'new'}
    elsif type == "Recruiter"
      chosen_path = {controller: 'recruiters', action: 'new'}
    end
  end

  def update
  end

  def destroy
  end
end

CareerFairTracker/app/helpers/admins_helper.rb
module AdminsHelper
end

CareerFairTracker/app/helpers/application_helper.rb
module ApplicationHelper
end

CareerFairTracker/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

CareerFairTracker/app/helpers/events_helper.rb
module EventsHelper
end

CareerFairTracker/app/helpers/home_helper.rb
module HomeHelper
end

CareerFairTracker/app/helpers/recruiters_helper.rb
module RecruitersHelper
end

CareerFairTracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

CareerFairTracker/app/helpers/students_helper.rb
module StudentsHelper
end

CareerFairTracker/app/helpers/users_helper.rb
module UsersHelper
end

CareerFairTracker/app/helpers/welcome_helper.rb
module WelcomeHelper
end

CareerFairTracker/app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

CareerFairTracker/app/views/admins/dashboard.html.haml
%h3{:style => "text-align: right; float: right;"}= "#{@userTag}"
%h1{:style => "text-align: center;"}= "#{@user_type} Dashboard" 
%br 
= link_to "Logout", logout_path
%br
%br 
%p= "#{@welcome_message}"
%br
= link_to "Edit Profile", edit_admin_path(session[:user_id_for_their_type])
= link_to "Add Event", new_event_path
%br 
= link_to "Edit Events", events_path
%h2{:style => "text-align: center;"}= "Events" 
%br
%table
    %thead 
        %tr 
            %th Event Name 
            %th Event Date 
            %th Start Time 
            %th End Time  
            %th 
    %tbody 
        -@events.each do |event|
            %tr.event_table_row 
                %td= event.name
                %td= event.event_date 
                %td= event.start_time 
                %td= event.end_time
                %td= link_to "View Attendance", event_path(event)
%br

CareerFairTracker/app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admin_dashboard_path %>

CareerFairTracker/app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>
<a href="/dashboard"/> Back to Dashboard
<h1 style="text-align:center;">Admins</h1>
<br/>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.first_name %></td>
        <td><%= admin.last_name %></td>
        <td><%= admin.email %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

CareerFairTracker/app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

CareerFairTracker/app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @admin.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @admin.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back to Dashboard', admin_dashboard_path %>

CareerFairTracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareerFairTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>