CareerFairTracker/config/routes.rb
Rails.application.routes.draw do

  get 'admin/dashboard', to: 'admins#dashboard', as: 'admin_dashboard'
  get 'recruiter/dashboard', to: 'recruiters#dashboard', as: 'recruiter_dashboard'
  get 'student/dashboard', to: 'students#dashboard', as: 'student_dashboard'
  
  resources :admins
  delete 'events', to: 'events#destroy'
  resources :events
  resources :recruiters
  root 'home#index'
  post 'users', to: 'users#create', as: 'user'
 
  post 'signup', to: 'users#create', as: 'signup'
  get 'signup', to: 'users#new'
  
  get 'dashboard', to: 'dashboards#index', as: 'dashboard'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  # post '/users' => 'users#create'
  # match '/users', to: 'users#create', as: 'dashboard', via: :post
  # match '/dashboards' => 'dashboards#index', via: :post
  match '/logins' => 'logins#index', via: :get
  match '/logins' => 'logins#index', via: :post
  
  # post '/dashboards/:username/display' => 'dashboards#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :home
  resources :students
  # resources :logins
  resources :dashboards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CareerFairTracker/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user, optional: true

    def self.to_csv
        attributes = %w(first_name last_name major)

        CSV.generate(headers: true) do |csv|
            csv << attributes

            all.each do |student|
                csv << student.attributes.values_at(*attributes)
            end
        end
    end
end

CareerFairTracker/app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def student_params
        params.require(:student).permit(:first_name, :last_name, :major, :expected_grad_month, :expected_grad_year)
    end

    def index
        @students = Student.all 
    end

    def show
        @student = Student.find(params[:id])
    end

    def new 
        @student = Student.new
    end

    def edit
    end

    def create
        @user = User.find(session[:user_id])
        @student = Student.new(student_params)
        @student.user = @user
        @student.user_id = @user.id
        if @student.save!
            redirect_to student_path(@student) and return
        end
        session[:user_id_for_their_type] = @student.id
        redirect_to student_dashboard_path and return
    end

    def dashboard
        @user = current_user
        if @user == nil
            redirect_to root_url and return
        end
        @user_tag = @user[:username]
        @student = Student.find_by user_id: @user.id
        @user_type = @user[:user_type]
        @welcome_message = "Welcome #{@user_tag}"
    end

    def update
    end

    def destroy
    end
end

CareerFairTracker/app/helpers/students_helper.rb
module StudentsHelper
end

CareerFairTracker/app/views/students/dashboard.html.haml
%h3{:style => "text-align: right; float: right;"}= "#{@userTag}"
%h1{:style => "text-align: center;"}= "#{@user_type} Dashboard" 
%br 
= link_to "Logout", logout_path
%br
%br 
%p= "#{@welcome_message}"
%br
= link_to "Edit Profile", edit_student_path(session[:user_id_for_their_type])
%br

CareerFairTracker/app/views/students/index.html.haml
%h1{ :style => "text-align: center;"} Career Fair Tracker 
%h2{ :style => "text-align: left;"} All Students 
%br 
= link_to "Add New Student", new_student_path
-# %br
-#= link_to "Edit/Remove a Student", remove_student_mode_path
%br 
%br
= link_to "Back to Dashboard", dashboards_path(bypass: :true)
%br
%table
    %thead 
        %tr 
            %th First Name 
            %th Last Name 
            %th Major 
            %th Expected Grad Month 
            %th Expected Grad Year
    %tbody 
        -@students.each do |student|
            %tr
                %td= student.first_name
                %td= student.last_name 
                %td= student.major 
                %td= student.expected_grad_month
                %td= student.expected_grad_year 

CareerFairTracker/app/views/students/new.html.haml
%h1{ :style => "text-align: center;"} Carreer Fair Tracker 
%h2{ :style => "text-align: left;"} Add New Student 
%br 
%br 
=form_tag(controller: :students, action: :create) do
    = label :student, :first_name, "First Name"
    = text_field(:student, :first_name)
    %br
    = label :student, :last_name, "Last Name"
    = text_field(:student, :last_name)
    %br
    = label :student, :major, "Major"
    = text_field(:student, :major)
    %br
    = label :student, :expected_grad_month, "Expected Graduation Month"
    = text_field(:student, :expected_grad_month)
    %br
    = label :student, :expected_grad_year, "Expected Graduation Year"
    = text_field :student, "expected_grad_year"
    %br
    = submit_tag "Submit"

CareerFairTracker/app/views/students/remove_student_mode.html.haml
%h2 All Students 

%br 
= link_to "Go Home", root_path
%br 
%br 
%table
    %thead 
        %tr 
            %th First Name 
            %th Last Name 
            %th Major 
            %th Expected Grad Month 
            %th Expected Grad Year
    %tbody 
        -@students.each do |student|
            %tr 
                %td= student.first_name
                %td= student.last_name 
                %td= student.major 
                %td= student.expected_grad_month
                %td= student.expected_grad_year  
                %td= link_to "Edit/Remove", controller: "students", action: 

CareerFairTracker/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Major:</strong>
  <%= @student.major %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back to Dashboard', student_dashboard_path %>